site:
  title: Bourbon Programming Language
  start_page: bourbon:ROOT:index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: ./bourbon-ui
  supplemental_files: ./docs/supplemental-ui

output:
  dir: ./build/site

asciidoc:
  extensions:
    - asciidoctor-kroki
