<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bourbon.txt</string>
	</array>
	<key>name</key>
	<string>Bourbon Scanner Test Case</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Matches header and source section block (ignoring source highlighting)</string>
			<key>begin</key>
			<string>\A(={3,})\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.separator.header.bourbon-test</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(-{3,})\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.separator.bourbon-test</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Actual header metadata block</string>
					<key>begin</key>
					<string>\A(={3,})\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.separator.header.bourbon-test</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(={3,})\s*$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.separator.header.bourbon-test</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.+</string>
							<key>name</key>
							<string>entity.name.section.bourbon-test</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Expectation section separators</string>
			<key>match</key>
			<string>^(-{3,})\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.separator.bourbon-test</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Line comments in the expectations section</string>
			<key>match</key>
			<string>^\s*(#.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.bourbon-test</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Diagnostic errors</string>
			<key>match</key>
			<string>^([✗\x{F057}]|\s)*\b(error)\b\s*(\[[a-zA-Z0-9]+\])?\s*(:)\s*(.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.symbol.diagnostic.bourbon-test</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.severity.diagnostic.bourbon-test</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.code.diagnostic.bourbon-test</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.diagnostic.bourbon-test</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.message.diagnostic.bourbon-test</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Diagnostic warnings</string>
			<key>match</key>
			<string>^([⚠\x{F071}]|\s)*\b(warning)\b\s*(\[[a-zA-Z0-9]+\])?\s*(:)\s*(.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.symbol.diagnostic.bourbon-test</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.severity.diagnostic.bourbon-test</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.code.diagnostic.bourbon-test</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.diagnostic.bourbon-test</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.message.diagnostic.bourbon-test</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Diagnostic info and notes</string>
			<key>match</key>
			<string>^([ℹ✔\x{F05A}]|\s)*\b(note|info)\b\s*(\[[a-zA-Z0-9]+\])?\s*(:)\s*(.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bold.info.symbol.diagnostic.bourbon-test</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.info.severity.diagnostic.bourbon-test</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.code.diagnostic.bourbon-test</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.diagnostic.bourbon-test</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.message.diagnostic.bourbon-test</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Diagnostic location link</string>
			<key>match</key>
			<string>^\s*(--&gt;)\s*([^:]+)\s*(:)\s*([0-9]+)\s*(:)\s*([0-9]+)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.location.bourbon-test</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.filename.bourbon-test</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.location.bourbon-test</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.line.bourbon-test</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.location.bourbon-test</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.column.bourbon-test</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Diagnostic empty/gutter line</string>
			<key>match</key>
			<string>^\s*(\|)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.gutter.bourbon-test</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Diagnostic source line preview</string>
			<key>match</key>
			<string>^\s*([0-9]+)\s*(\|)\s*(.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.line-number.gutter.bourbon-test</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.gutter.bourbon-test</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.raw.source-code.diagnostic.bourbon-test</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Diagnostic label underline line</string>
			<key>match</key>
			<string>^\s*(\|)\s*(\s*)(\^+)\s*(.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.gutter.bourbon-test</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.raw.source-code.diagnostic.bourbon-test</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.underline.diagnostic.bourbon-test</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.message.label.bourbon-test</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Token assertion parsing</string>
			<key>match</key>
			<string>^\s*([A-Z_][A-Z0-9_]*)\s*(.*?)\s*(@)\s*([0-9]+)(?:\s*\[\s*([0-9]+)\s*(\.\.)\s*([0-9]+)\s*\])?\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.token.bourbon-test</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.lexeme.bourbon-test</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.at.bourbon-test</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.column.bourbon-test</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.offset.start.bourbon-test</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.range.bourbon-test</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.offset.end.bourbon-test</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.bourbon-test</string>
	<key>uuid</key>
	<string>4F2F1B2E-6D7C-4C9D-A32F-5F1E2B0C3A4D</string>
</dict>
</plist>
